version: "2"
services:
 elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.1"
  container_name: elasticsearch
  environment:
   - discovery.type=single-node
   - indices.memory.index_buffer_size=20%
   - bootstrap.memory_lock=true
   - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
   - xpack.security.enabled=true
   - xpack.security.audit.enabled=true
   - ELASTIC_PASSWORD=somethingsecret
  ulimits:
    memlock:
      soft: -1
      hard: -1
  ports:
   - "9200:9200"
  networks:
   - eknetwork
 kibana:
  depends_on:
   - elasticsearch
  image: "docker.elastic.co/kibana/kibana:7.15.1"
  ports:
   - "5601:5601"
  environment:
   - ELASTICSEARCH_URL=http://localhost:9200
   - ELASTICSEARCH_USERNAME=elastic
   - ELASTICSEARCH_PASSWORD=somethingsecret
  networks:
   - eknetwork
networks:
 eknetwork:
  driver: bridge