@startuml architecture
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

Person(admin, "Browser", $sprite="user")
System_Boundary(webserver, "Web Server") {
    Container(apache, "Apache Server", "php", $descr="Main web server")
    Container(filesystem, "Logs", "txt", $descr="All logs")
    Rel(apache, filesystem, "generates", "https")
    Rel(admin, apache, "browses", "https")
}

System_Boundary(monitoring, "Monitoring") {
    Container(log, "Log Resync", "batch", $descr="Clean and resync all the logs")
    Container(es, "Log Index", "Elasticsearch", $descr="Indices of all logs")
    Rel_L(log, filesystem, "read", "https")
    Rel_R(log, es, "write", "https")
}

@enduml
