@startuml high-level

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(web, "Web"){
  System(webserver, "Webserver")
  System(logs, "Logs")
  Rel_R(webserver, logs, "save", "fs")
}

System_Boundary(monitoring, "Monitoring/Alerting") {
  
  System(batch, "Batch")
  System(index, "ElasticSearch")
  System(alerting, "Alerting")
  System(mailer, "Mail Sender")

  Rel_L(batch, logs, "read", "fs")
  Rel_U(batch, index, "write", "https")
  Rel_L(alerting, index, "read", "https")
  Rel_D(alerting, mailer, "send email", "smtp")
}


@enduml